---
# - hosts: master
#   gather_facts: no
#   tasks:
#   - name: Command
#     shell:
#       cmd: "kubeadm token create --print-join-command"
#     register: foo

# - hosts: worker
#   gather_facts: no
#   tasks:
#   - name: Check on master's foo
#     debug:
#       var: hostvars.{{ groups['master'][0] }}.foo

- hosts: master
  tasks:
  - name: Check OS
    debug:
      var: ansible_facts['distribution']
    when: ansible_facts['os_family'] == "RedHat"